apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-deployment
  namespace: kubernetes
  labels:
    app: hello
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello
template:
  metadata:
    labels:
      app: hello
  spec:
    containers:
      - name: hello
        image: danryderbingo/kubenretes:v1
        imagePullPolicy: IfNotPresent